name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: git-acm-linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: git-acm-darwin-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: git-acm-windows-x86_64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Prepare Release
        shell: bash
        run: |
          # Copy binary with proper permissions
          if [ "${{ matrix.platform.os }}" = "windows-latest" ]; then
            cp "target/${{ matrix.platform.target }}/release/git-acm.exe" "${{ matrix.platform.name }}"
          else
            cp "target/${{ matrix.platform.target }}/release/git-acm" "${{ matrix.platform.name }}"
            # Ensure binary is executable
            chmod +x "${{ matrix.platform.name }}"
          fi

          # Generate checksum files
          if [ "${{ matrix.platform.os }}" = "windows-latest" ]; then
            certutil -hashfile "${{ matrix.platform.name }}" SHA256 | grep -v "^SHA256" | grep -v "^CertUtil" | tr -d " \t\r\n" > "${{ matrix.platform.name }}.sha256"
          elif [ "${{ matrix.platform.os }}" = "macos-latest" ]; then
            shasum -a 256 "${{ matrix.platform.name }}" | cut -d ' ' -f 1 > "${{ matrix.platform.name }}.sha256"
          else
            sha256sum "${{ matrix.platform.name }}" | cut -d ' ' -f 1 > "${{ matrix.platform.name }}.sha256"
          fi

          # Show generated checksum for verification in logs
          echo "Generated checksum for ${{ matrix.platform.name }}:"
          cat "${{ matrix.platform.name }}.sha256"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ matrix.platform.name }},${{ matrix.platform.name }}.sha256
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactContentType: application/octet-stream # Ensure binary format is preserved
